name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd app
          pytest

  dockerize:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          cd app
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cloudcoreops:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloudcoreops:latest

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name cloudcoreops
      - name: Deploy to EKS
        run: |
          kubectl apply -k k8s/base/
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/cloudcoreops-app

  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        run: echo "Deployment and monitoring steps would be triggered here." 