name: Notify Slack
on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Infracost", "Trivy Scan"]
    types: [completed]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Build/Scan/Cost report for ${{ github.repository }}: ${{ github.workflow }} - ${{ github.event.workflow_run.conclusion }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 