name: Performance Test
on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]
    branches: [staging]
jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install k6
        run: sudo apt-get install -y k6
      - name: Run k6
        run: k6 run k6/loadtest.js 