name: Trivy Scan
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: 'dina0elsergani/cloudcoreops:latest' 