name: Uptime Check
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Uptime Check
        run: bash monitoring/uptime/uptime-check.sh 