apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcoreops-prod
spec:
  project: default
  source:
    repoURL: 'https://github.com/dina0elsergani/CloudCoreOps.git'
    path: k8s/overlays/prod
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 