apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcoreops-dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/dina0elsergani/CloudCoreOps.git'
    path: k8s/overlays/dev
    targetRevision: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 