apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.yourdomain.com"
    roleName: "cloudcoreops-app"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/cloudcoreops"
        secretKey: "db_password" 